name: mcr-py

channels:
  - conda-forge
  - defaults

dependencies:
  - ipykernel
  - pandas
  - geopandas
  - tqdm
  - pyrosm
  - numpy<1.24.0 # pyrosm does not support numpy 1.24.0 yet
  - shapely<2.0.0 # pyrosm does not support shapely 2.0.0 yet
  - osmnx
  - networkx
  - python-igraph
  - ipywidgets
  - typer
  - shellingham
  - rich
  - maturin
  - polars
  - pyarrow
  - folium
  - pytest
  - h3
  # - h3py
  - scipy
  - overpy
  - joblib
  - pip
  - scikit-learn
  - scikit-learn-extra
  - pip:
      - h3
