GROCERY_ATTRIBUTES = [
    ("shop", "alcohol"),
    ("shop", "bakery"),
    ("shop", "beverages"),
    ("shop", "brewing supplies"),
    ("shop", "butcher"),
    ("shop", "cheese"),
    ("shop", "chocolate"),
    ("shop", "coffee"),
    ("shop", "confectionery"),
    ("shop", "convenience"),
    ("shop", "deli"),
    ("shop", "dairy"),
    ("shop", "farm"),
    ("shop", "frozen food"),
    ("shop", "greengrocer"),
    ("shop", "health food"),
    ("shop", "ice-cream"),
    ("shop", "pasta"),
    ("shop", "pastry"),
    ("shop", "seafood"),
    ("shop", "spices"),
    ("shop", "tea"),
    ("shop", "water"),
    ("shop", "supermarket"),
    ("shop", "department store"),
    ("shop", "general"),
    ("shop", "kiosk"),
    ("shop", "mall"),
]
EDUCATION_ATTRIBUTES = [
    ("amenity", "college"),
    ("amenity", "driving school"),
    ("amenity", "kindergarten"),
    ("amenity", "language school"),
    ("amenity", "music school"),
    ("amenity", "school"),
    ("amenity", "university"),
]
HEALTH_ATTRIBUTES = [
    ("amenity", "clinic"),
    ("amenity", "dentist"),
    ("amenity", "doctors"),
    ("amenity", "hospital"),
    ("amenity", "nursing home"),
    ("amenity", "pharmacy"),
    ("amenity", "social facility"),
]
BANKS_ATTRIBUTES = [
    ("amenity", "atm"),
    ("amenity", "bank"),
    ("amenity", "bureau de change"),
    ("amenity", "post office"),
]
PARKS_ATTRIBUTES = [
    ("leisure", "park"),
    ("leisure", "dog park"),
]
SUSTENANCE_ATTRIBUTES = [
    ("amenity", "restaurant"),
    ("amenity", "pub"),
    ("amenity", "bar"),
    ("amenity", "cafe"),
    ("amenity", "fast-food"),
    ("amenity", "food court"),
    ("amenity", "ice-cream"),
    ("amenity", "biergarten"),
]
SHOPS_QUERY = [
    ("shop", "department store"),
    ("shop", "general"),
    ("shop", "kiosk"),
    ("shop", "mall"),
    ("shop", "wholesale"),
    ("shop", "baby goods"),
    ("shop", "bag"),
    ("shop", "boutique"),
    ("shop", "clothes"),
    ("shop", "fabric"),
    ("shop", "fashion accessories"),
    ("shop", "jewelry"),
    ("shop", "leather"),
    ("shop", "watches"),
    ("shop", "wool"),
    ("shop", "charity"),
    ("shop", "secondhand"),
    ("shop", "variety store"),
    ("shop", "beauty"),
    ("shop", "chemist"),
    ("shop", "cosmetics"),
    ("shop", "erotic"),
    ("shop", "hairdresser"),
    ("shop", "hairdresser supply"),
    ("shop", "hearing aids"),
    ("shop", "herbalist"),
    ("shop", "massage"),
    ("shop", "medical supply"),
    ("shop", "nutrition supplements"),
    ("shop", "optician"),
    ("shop", "perfumery"),
    ("shop", "tattoo"),
    ("shop", "agrarian"),
    ("shop", "appliance"),
    ("shop", "bathroom furnishing"),
    ("shop", "do-it-yourself"),
    ("shop", "electrical"),
    ("shop", "energy"),
    ("shop", "ﬁreplace"),
    ("shop", "ﬂorist"),
    ("shop", "garden centre"),
    ("shop", "garden furniture"),
    # ("shop", "gas"),
    ("amenity", "fuel"),
    ("shop", "glaziery"),
    ("shop", "groundskeeping"),
    ("shop", "hardware"),
    ("shop", "houseware"),
    ("shop", "locksmith"),
    ("shop", "paint"),
    ("shop", "security"),
    ("shop", "trade"),
    ("shop", "antiques"),
    ("shop", "bed"),
    ("shop", "candles"),
    ("shop", "carpet"),
    ("shop", "curtain"),
    ("shop", "doors"),
    ("shop", "ﬂooring"),
    ("shop", "furniture"),
    ("shop", "household linen"),
    ("shop", "interior decoration"),
    ("shop", "kitchen"),
    ("shop", "lighting"),
    ("shop", "tiles"),
    ("shop", "window blind"),
    ("shop", "computer"),
    ("shop", "electronics"),
    ("shop", "hiﬁ"),
    ("shop", "mobile phone"),
    ("shop", "radio-technics"),
    ("shop", "vacuum cleaner"),
    ("shop", "bicycle"),
    ("shop", "boat"),
    ("shop", "car"),
    ("shop", "car"),
    ("shop", "repair"),
    ("shop", "car parts"),
    ("shop", "caravan"),
    ("shop", "fuel"),
    ("shop", "ﬁshing"),
    ("shop", "golf"),
    ("shop", "hunting"),
    ("shop", "jet ski"),
    ("shop", "military surplus"),
    ("shop", "motorcycle"),
    ("shop", "outdoor"),
    ("shop", "scuba diving"),
    ("shop", "ski"),
    ("shop", "snowmobile"),
    ("shop", "swimming pool"),
    ("shop", "trailer"),
    ("shop", "tyres"),
    ("shop", "art"),
    ("shop", "collector"),
    ("shop", "craft"),
    ("shop", "frame"),
    ("shop", "games"),
    ("shop", "model"),
    ("shop", "music"),
    ("shop", "musical instrument"),
    ("shop", "photo"),
    ("shop", "camera"),
    ("shop", "trophy"),
    ("shop", "video"),
    ("shop", "videogames"),
    ("shop", "anime"),
    ("shop", "books"),
    ("shop", "gift"),
    ("shop", "lottery"),
    ("shop", "newsagent"),
    ("shop", "stationery"),
    ("shop", "ticket"),
    ("shop", "bookmaker"),
    ("shop", "cannabis"),
    ("shop", "copy node"),
    ("shop", "drycleaning"),
    ("shop", "e-cigarette"),
    ("shop", "funeral directors"),
    ("shop", "laundry"),
    ("shop", "moneylender"),
    ("shop", "party"),
    ("shop", "pawnbroker"),
    ("shop", "pet"),
    ("shop", "pet"),
    ("shop", "grooming"),
    ("shop", "pest control"),
    ("shop", "pyrotechnics"),
    ("shop", "religion"),
    ("shop", "storage rental"),
    ("shop", "tobacco"),
    ("shop", "toys"),
    ("shop", "travel agency"),
    ("shop", "vacant"),
    ("shop", "weapons"),
    ("shop", "outpost"),
]

X_MINUTE_CITY_QUERIES = [
    ("grocery", GROCERY_ATTRIBUTES),
    ("education", EDUCATION_ATTRIBUTES),
    ("health", HEALTH_ATTRIBUTES),
    ("banks", BANKS_ATTRIBUTES),
    ("parks", PARKS_ATTRIBUTES),
    ("sustenance", SUSTENANCE_ATTRIBUTES),
    ("shops", SHOPS_QUERY),
]
