name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up conda environment with mamba
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yaml
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
